/* USER_SIGNUP */
export const USER_SIGNUP_STARTED = "USER_SIGNUP_STARTED";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";
export const USER_SIGNUP_PASSNOTEQUAL = "USER_SIGNUP_PASSNOTEQUAL";

/* USER_LOGIN */
export const USER_LOGIN_STARTED = "USER_LOGIN_STARTED";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

/* USER_TOKEN ACCESS */
export const USER_ACCESS_TOKEN_STARTED = "USER_ACCESS_TOKEN_STARTED";
export const USER_ACCESS_TOKEN_SUCCESS = "USER_ACCESS_TOKEN_SUCCESS";
export const USER_ACCESS_TOKEN_FAILURE = "USER_ACCESS_TOKEN_FAILURE";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_PRELOGIN = "USER_PRELOGIN";

/* USER_TOKEN REFRESH */
export const USER_REFRESH_TOKEN_STARTED = "USER_REFRESH_TOKEN_STARTED";
export const USER_REFRESH_TOKEN_SUCCESS = "USER_REFRESH_TOKEN_SUCCESS";
export const USER_REFRESH_TOKEN_FAILURE = "USER_REFRESH_TOKEN_FAILURE";
export const USER_REFRESH_TOKEN_INT = "USER_REFRESH_TOKEN_INT";
