
export const USER_SIGNUP_PASSNOTEQUAL = "USER_SIGNUP_PASSNOTEQUAL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_UPDATE_NAME = "USER_UPDATE_NAME";

